spring:
  profiles.active: local
---
spring:
  profiles: local
  
  data:
   mongodb:
    uri: mongodb://localhost/sjcnewsdb
---
spring:
  profiles: production
    
  data:
   mongodb:
    uri: ${mongo.url}
    
    
url:
  feed: http://www.sjc.sp.gov.br/pmsjc_paginas/rss.aspx
